### ISSUE TITLE
Error with Make Install

### ISSUE THREAD

**Issue by Starlord0006** [Quedale/OnvifDeviceManager#12]
All the process goes through but at the MAKE INSTALL I get:

make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/home/starlord/OnvifDeviceManager'

Any ideas I'm running Ubuntu 22.04.3 LTS

Thanks

**Comment by Quedale** [comment]
Almost everything was reviewed and updated since this issue was reported.
Closing since it is most likely out-dated by now.

Feel free to open a new issue if you are still experiencing it.
